### PR TITLE
Improvements

### PR DESCRIPTION
**Pull request by ArCorvus**
1. Fix for FlyTo node. Able to use in SimpleParellel node
2. Added for FlyTo ability to recalculate path on the fly with threshold. If FlightLocationKey is changed (> threshold) FlyTo tries to recalculate a path.
3. Added function to get a NavigationManager that is built around specified Actor. It gives an ability to use several NavigationManagers on one map. Managers should not be overlapped. There is ambiguity if Actor is located in 2+ Managers in the moment when we try to get manager for specific Actor.
4. Added EQS Task that checks if Location is navigable. Optionally search for a random navigable location around specified one.
5. Exposed CanNavigate(Location) to BP

### CODE REVIEW

**Comment by VSZue** [comment]
Hi, thank you for this excellent contribution!

I'm in the middle of merging a lot of code from my local branch and some other community changes that been sent to me too, so I now need to figure out how to merge all three things together :)

**Comment by ArCorvus** [comment]
Thank you for this excellent plugin! 👍 
If something do not fit with other changes feel free to ask me to remake. Also I'm open for critic if something that I have made is not that way it was intended to be )

**Comment by VSZue** [comment]
Merged! Also, official 4.17 release for the plugin is out with some very major features.

Check it out on [this forum post](https://forums.unrealengine.com/showthread.php?140601-DoN-s-3D-Pathfinding-for-Flying-A-I-Support-Thread&p=752743&viewfull=1#post752743)! Github branch will be updated soon.

**Comment by VSZue** [comment]
Master branch has been updated with latest 4.17 code!

PS: I've credited you for your contribution in the [forum post](https://forums.unrealengine.com/showthread.php?140601-DoN-s-3D-Pathfinding-for-Flying-A-I-Support-Thread&p=752743&viewfull=1#post752743) :)

**Pull request merged**
